### ISSUE TITLE
pathRoot?

### ISSUE THREAD

**Issue by kokujin** [garygreen/lightrouter#1]
Can you explain exactly the usage of the option "pathRoot"? I took a look at the source and the test, but I still was not sure of its usage. Thanks

**Comment by rajakhoury** [comment]
@garygreen How would you handle routes Urls prefixed with a locale ;

landing route: 
domain.com 
domain.com/es
domain.com/en

About route:
domain.com/about
domain.com/es/about
domain.com/en/about

What I tried is setting the pathRoot to domain.com + Locale code but it doesn't work for all routes - How would you do it ?
