### ISSUE TITLE
Only home route works

### ISSUE THREAD

**Issue by jsantari** [garygreen/lightrouter#3]
I can't get any route to work other then the home route. I am testing in a subdomain mr.nwcomp.com and have this setup as a simple test based on sample code. No matter what I try I get a 404 on the users path.

```
var router = new LightRouter({
    type: 'path',
    path: '',
    pathRoot: '',
    routes: {
        '': function(params) {alert('home')},
        'users/{id}': function(params) { console.log('showing user', params.id); }
    }
}).run();
```

Never mind - I figured out what I was doing wrong.

**Comment by garygreen** [comment]
> Never mind - I figured out what I was doing wrong.

What was it? :)

**Comment by jsantari** [comment]
I was trying to call other routes besides / directly on address bar. If 
I did it from page links they worked. I assume that was by design?

On 1/18/2016 1:09 PM, Gary Green wrote:

> ```
> Never mind - I figured out what I was doing wrong.
> ```
> 
> What was it? :)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/garygreen/lightrouter/issues/3#issuecomment-172625380.

## 

Jim Santarius
NCC Technology Group

**Comment by ariesdane** [comment]
Why is this issue still open?
